<a href="https://colab.research.google.com/github/3zero69/-/blob/main/0930_%ED%8C%8C%EC%9D%B4%EC%8D%AC%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EC%99%84%EB%B2%BD%EA%B0%80%EC%9D%B4%EB%93%9C_p_87_131.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#CHAPTER 02 사이킷런으로 시작하는 머신러닝
 
 



## 01. 사이킷런 소개와 특징
* 사이킷런: 파이썬 기반의 머신러닝을 위한 가장 쉽고 효율적인 개발 라이브러리
 - 텐서플로, 케라스 등 딥러닝 전문 라이브러리 존재
 - 사이킷런은 파이썬 ML 라이브러리
* 사이킷런의 특징
  - 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향할 정도로 쉽고 가장 파이썬 스러운 API 제공
  - 머신러닝을 위한 매우 다양한 알고리즘 개발을 위한 편리한 프레임워크와 API 제공
  - 오랜 기간 실전 환경에서 검증, 매우 많은 환경에서 사용되는 성숙한 라이브러리

In [ ]:
import sklearn
print(sklearn.__version__) # 사이킷런 버전 확인

1.0.2


##02. 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기

- 머신러닝 모델: 붓꽃 데이터 세트로 붓꽃의 품종을 분류(Classification)
  - 붓꽃 데이터세트 : 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 피쳐(Feature)를 기반으로 품종 예측 

### 분류(Classification)
- 대표적인 지도학습(Supervised Learning) 방법
  - 지도학습: 학습을 위한 다양한 피쳐와 분류 결정값인 레이블(Label) 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측
  - 명확한 정답이 주어진 데이터를 먼저 학습한 뒤 미지의 정답을 예측하는 방식
    - 학습 데이터 세트: 학습을 위해 주어진 데이터 세트
    - 테스트 데이터 세트: 머신러닝 모델의 예측 성능을 평가하기 위해 별도로 주어진 데이터 세트

사이킷런에서 사용할 모듈 임포트

In [ ]:
from sklearn.datasets import load_iris # 붓꽃 데이터 세트 생성
from sklearn.tree import DecisionTreeClassifier # ML 알고리즘 : 의사결정트리(Decision Tree) 알고리즘
from sklearn.model_selection import train_test_split # 데이터 세트를 학습 데이터와 테스트 데이터로 분리

> * 사이킷런 패키지 내의 모듈명은 skleran으로 시작하는 명명규칙
 - `sklearn.tree` : 사이킷런에서 자체적으로 제공하는 데이터 세트 생성 모듈
 *`sklearn.model_selection` : 학습 데이터와 검증 데이터, 예측 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 다양한 모듈의 모임
   - 하이퍼 파라미터: 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 마라미터, 머신러닝 알고리즘의 성능 튜닝 가능


붓꽃 데이터 세트 로드 후, 데이터 구조 분석 (피처들과 데이터 값 구성)

In [ ]:
import pandas as pd

#붓꽃 데이터 세트 로딩
iris = load_iris()

#iris.data는 Iris 데이터 세트에서 feature 만으로 된 데이터를 numpy로 갖고 있음
iris_data = iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 갖고 있음
iris_label = iris.target
print('iris target 값: ', iris_label)
print('iris target 명: ', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target 값:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명:  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

>  * 피처 : sepal length, sepal width, petal length, petal width
 * 레이블 : 0,1,2 세가지 값( 0이 setosa, 1이 versicolor, 2가 virginica )

학습용 데이터와 테스트용 데이터 분리



In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

> 
* `train_test_split()` : 학습 데이터와 테스트 데이터를 test_size 파라미터 입력 값의 비율로 분할
 - 예) test_size = 0.2 ; 전체 데이터 중 테스트 데이트 20%, 학습 데이터 80% 로 데이터 분할
 - 파라미터
   - iris_data : 피처 데이터 세트
   - iris_label: 레이블 데이터 세트
   - test_size=0.2 : 전체 데이터 세트 중 테스트 데이터 세트의 비율
   - random_state : 호출 시 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값 ( 미지정시, 수행할 때마다 다른 학습/테스트용 데이터를 만들 수 있음)

>   학습용 피처 데이터 세트를 X_train으로, 테스트용 피처 데이터 세트를 X_test로, 학습용 레이블 데이터 세트를 y_train으로, 테스트용 레이블 데이터 세트를 y_test로 반환[링크 텍스트

의사결정 트리(머신러닝 분류 알고리즘)를 이용해 학습과 예측 수행

In [ ]:
#DecisionTreeClassfier를 객체로 생성
dt_clf = DecisionTreeClassifier(random_state=11)

#학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

> 학습 함수 : `fit(학습용 피처 데이터 속성, 결정값 데이터 세트)`

In [ ]:
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)


> 예측 함수: `predict(테스트용 피처 데이터 세트)`
- 학습데이터가 아닌 다른 데이터를 이용해야 함 (테스트 데이터 세트 이용)

예측 성능 평가 - 정확도 측정

In [ ]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


* 정확도 측정 
 - 정확도: 예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는지를 평가하는 지표

> 정확도 측정 함수 : `accuracy_score(실제 레이블 데이터 세트, 예측 레이블 데이터 세트)`

*정리 *
1. **데이터 세트 분리**: 데이터를 학습 데이터와 테스트 데이터로 분리
2. **모델 학습**: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습
3. **예측 수행**: 학습된 ML 모델을 이용해 테스트 데이터의 분류(즉, 붓꽃 종류)를 예측
4. **평가**: 예측된 결과값과 테스트 데이터의 실제 결과값을 비교해 ML 모델 성능을 평가

## 03. 사이킷런의 기반 프레임워크 익히기

* Estimator 클래스
 - 분류 알고리즘 구현 클래스 : Classifier
 - 회귀 알고리즘 구현 클래스 : Regressor
 
1. evaluatio 함수 *cross_val_score()*, 하이퍼 파라미터 튜닝을 지원하는 클래스 *GridSearchCV* 의 경우 Estimator를 인자로 받음
2. 인자로 받은 Estimator에 대해서 cross_val_score(), GridSearchCV.fit() 함수 내에서 Estimator의 fit()과 predict()를 호출해서 평가를 하거나 하이퍼 파라미터 튜닝 수행



### 사이킷런의 주요 모듈
교재 p.94-95

###내장된 예제 데이터 세트
교재 p.96-97
* 분류나 회귀를 연습하기 위한 
 - 딕셔너리 형태
 - 키 
   - data : 데이터 세트 - 넘파이 배열 타입
   - target : 레이블 값(분류)/ 숫자 결과값(회귀) 데이터 세트 - 넘파이 배열 타입
   - target_name : 개별 레이블의 이름 - 넘파이 배열 또는 파이썬 리스트 타입
   - featur_names : 피처의 이름 - 넘파이 배열 또는 파이썬 리스트 타입
   - DESCR : 데이터 세트에 대한 설명과 각 피처의 설명 - 스트링 타입
* 분류나 클러스터링을 위해 표본 데이터로 생성될 수 있는 데이터 세트


cf. 피처의 데이터 값을 반환받기 위해서는 내장 데이터 세트 API를 호출한 뒤에 그 key 값을 지정 

붓꽃 데이터 세트 생성

In [ ]:
from sklearn.datasets import load_boston
iris_data = load_iris() #  데이터 세트에 내장되어 있는 대부분의 데이터 세트는 딕셔너리 형태의 값을 반환

> API 반환 결과; sklearn.utils.Bunch 클래스
 * Bunch 클래스는 파이썬 딕셔너리 자료형과 유사


In [ ]:
keys = iris_data.keys() # 딕셔너리 형태의 키값 확인
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


피처 데이터 값 추출 
: `데이터세트.data / 데이터세트['data']`

load_iris() 가 반환하는 객체의 키인 feature_names, target_name, data, target 이 가리키는 값 출력

In [ ]:
print('\n feature_names 의 type:', type(iris_data.feature_names))
print('feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print('target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data의 shape:', iris_data.data.shape)
print(iris_data.data)

print('\n target의 type:', type(iris_data.target))
print('target_namesdml shape:', iris_data.target.shape)
print(iris_data.target)


 feature_names 의 type: <class 'list'>
feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.

## 04. Model Selection 모듈 소개
* model_selection 모듈
 - 학습 데이터와 테스트 데이터 세트를 분리, 교차 검증 분할 및 평가, 그리고 Estimatior의 하이퍼 파라미터를 튜닝하기 위한 다양한 함수와 클래스 제공

 ### 학습/테스트 데이터 세트 분리 : **train_test_split()** 
* 파라미터
 - 첫번째 파라미터 피처 데이터 세트, 두번째 파라미터 레이블 데이터 세트
 - 선택적 파라미터
   * test_size : 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링할 것인가를 결정함 ( 디폴트는 0.25 )
   * train_size : 전체 데이터에서 학습용 데이터 세트 크기를 얼마로 샘플링할 것이나 결정, test_size parameter를 통상적으로 사용하기 때문에 잘 사용하지 않음
   * shuffle : 데이터를 분리하기 전에 데이터를 미리 섞을지 결정, 디폴트는 True, 데이터를 분산시켜서 좀 더 효율적인 학습 및 테스트 데이터 세트를 만드는 데 사용
   * random_state :호출할 때마다 동일한 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 값
* 반환값: 튜플 형태 
 - 순차적으로 학습용 데이터 피처 데이터 세트, 
 - 테스트용 데이터의 피처 데이터 세트,
 - 학습용 데이터의 레이블 데이터 세트, 
 - 테스트용 데이터의 레이블 데이터 세트가 반환

붓꽃 데이터 세트 학습

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

df_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.3, random_state = 121)


학습데이터 기반으로 DecisionTreeClassifier 학습 후 해당 모델을 이용해 예측 정확도 측정

In [ ]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


### 교차 검증
* 배경
 * 별도의 테스트용 데이터를 이용하는 방법 역시 과적합에 취약함
   - 과적합(Overfitting) : 모델이 학습 데이터에만 과도하게 최적화 되어, 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어지는 것
  * 고정된 학습 데이터와 테스트 데이터로 평가를 하다 보면 테스트 데이터에만 최적의 성능을 발휘할 수 있도록 모델을 유도하는 경향이 생김
  * 해당 테스트 데이터에만 과적합 되는 학습 모델의 생성으로 다른 테스트용 데이터가 들어올 경우에는 성능이 저하

* **교차검증** : 별도의 여러 세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평가를 수행하는 것
 - 각 세트에서 수행한 평가 결과에 따라 하이퍼 파라미터 튜닝 등의 모델 최적화를 더 손쉽게 가능
 


**K 폴드 교차 검증**
: K 개의 데이터 폴드 세트를 만들어 K번 만큼 각 폴트 세트에 학습과 검증 평가를 반복적으로 수행하는 방법

* K = 5 인 경우 _ 5개의 폴드된 데이터 세트를 학습과 검증을 위한 데이터 세트로 변경하면서 5번 평가를 수행한 뒤, 이 5개의 평가를 평균한 결과를 가지고 예측 성능을 평가
1. 데이터 세트 K등분 나누기 
2. 학습 데이터 세트에서 학습 수행/검증 데이터 세트에서 평가를 수행 : 첫번째 반복에서는 처음부터 4개 등분을 학습 데이터 세트, 마지막 5번째 등분 하나를 검증 데이터 세트로 설정, 
3. 두번째 ~ K번째 반복에서 비슷한 학습과 평가 작업 수행 (단, 학습 데이터와 검증 데이터를 변경 : 검증데이터를 하나씩 당겨옴) 
4. K 개의 예측 평가를 구한 후, 이를 평균하여 K 폴드 평가 결과로 반영



In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
df_clf = DecisionTreeClassifier(random_state=156)

#5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기: ', features.shape[0]) 

붓꽃 데이터 세트 크기:  150


>  * KFold 객체는 split()을 호출하면 학습용/검증용 데이터로 분할할 수 있는 인덱스를 반환함
  - 실제로 학습용/검증용 데이터 추출은 반환된 인덱스를 기반으로 개발 코드에서 직접 수행해야함

KFold 객체의 split()을 호출해 교차 검증 수행 시마다 학습과 검증을 반복해 예측 정확도 측정

In [ ]:
n_iter = 0

#KFold 객체의 split()를 호출하면 폴드별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):  

  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1

  #반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 개별 iteration 별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도: 0.8333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9200000000000002


**Stratified K 폴드** : 불균형한 (imbalanced) 분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 K 폴드 방식
- K 폴드가 레이블 데이터 집합이 원본 데이터 집합의 레이블 분포를 학습 및 테스트 세트에 제대로 분배하지 못하는 경우의 문제를 해결
- Stratified K 폴드는 원본 데이텅의 레이블 분포를 먼저 고려한 뒤 이 분포와 동일하게 학습과 검증 데이터 세트를 분배함

In [ ]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포 : \n', label_train.value_counts())
  print('검증 레이블 데이터 분포 : \n', label_test.value_counts())
  iris_df['label'].value_counts()


## 교차 검증: 1
학습 레이블 데이터 분포 : 
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포 : 
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포 : 
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포 : 
 2    50
Name: label, dtype: int64


> 교차 검증 시마다 3개의 폴드 세트로 만들어지는 학습 레이블과 검증 레이블이 완전히 다른 값으로 추출
 
  - ex. 학습 레이블은 1,2 밖에 없으므로 0의 경우는 전혀 학습하지 못하므로 예측하지 못함

 * StratifiedKFold 를 사용하는 방법은 KFold를 사용하는 방법과 거의 비슷
 * 단 하나 큰 차이는 레이블 데이터 분포도에 따라 학습/검증 데이터를 나누기 때문에 split() 메서드에 인자로 피처 데이터 세트뿐만 아니라 레이블 데이터 세트도 반드시 필요

In [ ]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter +=1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [ ]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold의 split() 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
  #split()으로 반환도니 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  #학습 및 예측
  dt_clf.fit(X_train,y_train)
  pred = dt_clf.predict(X_test)

  #반복시마다 정확도 측정
  n_iter += 1
  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스 : {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

  #교차 검증별 정확도 및 평균 정확도 계산
  print('\n## 교차 검증별 정확도 : ', np.round(cv_accuracy,4))
  print('## 평균 검증 정확도 :', np.mean(cv_accuracy))


#1 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

## 교차 검증별 정확도 :  [0.98]
## 평균 검증 정확도 : 0.98

#2 교차 검증 정확도: 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

## 교차 검증별 정확도 :  [0.98 0.94]
## 평균 검증 정확도 : 0.96

#3 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도 :  [0.98 0.94 0.98]
## 평균 검증 정확도 : 0.9666666666666667


**교차 검증을 보다 간편하게 - cross_val_score()**


1.   폴드 세트 설정
2.   for 루프에서 반복으로 학습 및 테스트 데이터의 인덱스 추출
3. 반복적으로 학습과 예측 수행하고 예측 성능 반환

     `corss_val_score(estimator, X, y=None, scoring=None, cv=None, n_jobs=1, verbose=0, fit_params=None, pre_dispatch=2*n_jobs')`
- 주요 파라미터
  - estimator: 사이킷런의 분류 알고리즘 세트(Classifier / Regressor)
  - X: 피처 데이터 세트
  - y: 레이블 데이터 세트
  - scoring: 예측 성능 평가 지표
  - cv: 교차 검증 폴드 수
* 반환값: scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환
* 학습/테스트 세트 분할 방식
 - classifier 입력시, Stratified K 폴드 방식으로 레이블값의 분포에 따라 분할
 - regressor 입력시, K폴드 방식으로 분할 (Stratified 방식 분할 불가)


In [ ]:
# Import method from module
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score , cross_validate
from sklearn.datasets import load_iris

# 데이터셋 및 DecisionTreeClassifier 생성
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

# Feature 데이터셋과 Label 데이터셋 분리
data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuracy) , 교차 검증 세트는 3개 
scores = cross_val_score(dt_clf , data , label , scoring = 'accuracy',cv = 3)
print('교차 검증별 정확도:',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


### GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에
: 하이퍼 파라미터를 순차적으로 입력하면서 편리하게 최적의 파라미터를 도출할 수 있는 방안
* 


In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습데이타와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()
# parameter 들을 dictionary 형태로 설정
parameters = {'max_depth':[1,2,3],
              'min_samples_split':[2,3]}

In [ ]:
import pandas as pd

# param_grid의 하이퍼 파라미터들을 3개의 폴드로 나누어 테스트 수행
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True ) # refit=True 가 default / True 이면 가장 좋은 파라미터 설정으로 재학습   
# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)
# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', \
           'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

> * pandas 칼럼에는 수행할 때마다 적용된 개별 하이퍼 파라미터값을 나타냄
* rank_test_score : 하이퍼 파라미터별로 성능이 좋은 score 순위를 나타냄 (1이 가장 뛰어난 순위, 최적의 하이퍼 파라미터)
* mean_test_score : 개별 하이퍼 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평균값


In [ ]:
# best_params_ : 최고 성능을 나타낸 하이퍼 파라미터 값
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)

# best_score_ : 최고 성능을 나타낼 때, 모델의 성능 평가의 결과 값
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도: 0.9750


In [ ]:
# refit = True이면 최적 성능을 나타내는 하이퍼 파라미터로 Estimator를 학습해 best_estimator_에 저장
# GridSearchCV의 refit으로 이미 학습이 된 estimator 반환
estimator = grid_dtree.best_estimator_

# GridSearchCV의 best_estimator_는 이미 최적 하이퍼 파라미터로 학습이 됨
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도: 0.9667


## 05. 데이터 전처리
* 결손값 (NaN, NULL 값) 허용 안됨
  - Null 값은 고정된 다른 값으로 변환해야 함
     - 피처 값중 Null값이 얼마 되지 않는 경우, 피처의 평균값으로 간단히 대체
     - Null 값이 대부분이라면, 해당 피처는 드롭하는 것이 좋음
     - Null 값이 일정 수준 이상 되는 경우(중요도가 높은 피처, Null 값을 단순히 피처의 평균값으로 대체할 경우 예측 왜곡이 심하다면), 업무 로직을 검토해 정밀한 대체값을 선정해야 함
* 문자열 값을 입력값으로 허용하지 않음
  - 모든 문자열은 인코딩 되어 숫자형으로 변환해야 함
  - 카테고리형 피처: 코드값으로 표현
  - 텍스트형 피처: 피처 벡터화 등의 기법으로 벡터화하거나 불필요한 피처의 경우 삭제
    - 예) 주민번호, 단순 문자열 아이디의 경우 인코딩하지 않고 삭제

### 데이터 인코딩

1. **레이블 인코딩**
: 카테고리 피처 -> 코드형 숫자 값으로 변환
  - 주의 : '01','02' 와 같은 코드값 역시 문자열이므로 1,2 와 같은 숫자형으로 변환해야 함


In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 : ', labels)

인코딩 변환값 :  [0 1 4 5 3 3 2 2]


In [ ]:
print('인코딩 클래스 :', encoder.classes_)
# classes_속성값 :어떤 값으로 인코딩 됐는지 확인 0부터

인코딩 클래스 : ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
print('디코딩 원본값 : ', encoder.inverse_transform([4,5,2,0,1,1,3,3]))
# inverse_transform() : 인코딩된 값 다시 디코딩

디코딩 원본값 :  ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


* 문제점 
  - 일괄적인 숫자값으로 변환되면서 몇몇 ML 알고리즘에는 이를 적용할 경우 예측 성능이 떨어짐 (숫자값의 경우 크고 작음에 대한 특정이 작용하기 때문)
  - 그러나, 숫자 변환값은 단순 코드이기 때문에 숫자값에 따른 순서나 중요도로 인식되어서는 안됨
     -  회귀와 같은 ML 알고리즘에는 적용 x 
     - 트리 계열의 ML 알고리즘은 숫자의 특성을 반영하지 않으므로 적용 O

2. **원-핫 인코딩(One-Hot Encoding)**
: 피처 값의 유형에 따라 새로운 피처를 추가해 고유값에 해당하는 칼럼에만 1을 표시, 나머지 칼럼에는 0 표시

In [ ]:

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

#먼저 숫자값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

#2차원 데이터로 변경
labels = labels.reshape(-1,1)

#원핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원 핫 인코딩 데이터')
print(oh_labels.toarray())
print('원 핫 인코딩 데이터 차원')
print(oh_labels.shape)

원 핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원 핫 인코딩 데이터 차원
(8, 6)


* 판다스 원-핫 인코딩 지원 API : `.get_dummies()`
 - 사이킷런과 달리, 문자열 카테고리 값을 숫자형으로 변환할 필요 없이 바로 변환 가능

In [ ]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 피처 스케일링과 정규화 
: 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업

- **표준화 (Standardization)** : 데이터 피처 각각이 평균이 0, 분산이 1 인 가우시안 정규분포를 가진 값으로 변환하는 것

- **정규화 (Normalization**) : 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 것
  - 개별 데이터의 크기를 모두 똑같은 단위로 변경하는 것
  - 

**StandardScaler**
: 표준화 지원 클래스 
- 가우시안 분포를 가질 수 있도록 데이터 변환

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

#붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns = iris.feature_names)

print('feature들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


**MinMaxScaler**
: 데이터값을 0과 1 사이의 범위 값으로 변환(음수 값은 -1에서 1로 변환)
- 데이터 분포가 가우시안 분포가 아닌 경우에 적용

In [ ]:
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler 객체 생성
scaler = MinMaxScaler()

#MinMaxScaler로 데이터 세트 변환. fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 세트가 Numpy ndarray로 변환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature 들의 최솟값')
print(iris_df_scaled.min())
print('\nfeature들의 최댓값')
print(iris_df_scaled.max())

feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64



### 학습 데이터와 테스트 데이터의 스케일링 변환시 유의점


**테스트 데이터에 fit()을 적용할 경우의 문제점**
- 테스트 데이터에 다시 fit()을 적용하면 안되고, 학습 데이터로 이미 fit()이 적용된 Scaler 객체를 이용해 transform() 으로 변환해야 함


* fit_transform() 적용 시에도, 테스트 데이터에서는 절대 사용해서는 안됨



In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
#Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변경
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

#MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1 값으로 변환
scaler = MinMaxScaler()

#fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10 으로 설정
scaler.fit(train_array)

#1/10 scale로 train_array 데이터 변환함, 원본 10 -> 1로 변환됨
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 :', np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터 :', np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터 : [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터 : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


테스트 데이터 세트 변환시, fit() 호출해 스케일링 기준 정보를 다시 적용한 뒤 transform() 을 수행

In [ ]:
#MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정됨
scaler.fit(test_array)

#1/5 scale로 test_array 데이터 변환함 원본 5 ->1로 변환
test_scaled = scaler.transform(test_array)

#test_array의 scale 변환 출력
print('원본 test_array 데이터 : ', np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터 : ', np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터 :  [0 1 2 3 4 5]
Scale된 test_array 데이터 :  [0.  0.2 0.4 0.6 0.8 1. ]


> 학습 데이터와 테스트 데이터의 스켈링이 맞지 않음

해결

In [ ]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 :', np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터 :', np.round(train_scaled.reshape(-1),2))

# fit() 호출하지 않고 transform()만으로 변환해야함
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터 : ', np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터 : ', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터 : [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터 : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터 :  [0 1 2 3 4 5]
Scale된 test_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5]


$ 정리 
1. 가능하다면 전체 데이터의 스케일링 변환 적용 후, 학습과 테스트 데이터로 분리
2. (1)이 가능하지 않은 경우, 테스트 데이터 변환 시에는 fit()이나 fit_transform()이 아닌 학습데이터로 이미 fit()된 Scaler 객체를 이용해 transform()으로 변환